name: Axon Data Protection Config API

on:
  pull_request:

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 8
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: 8
          cache: 'maven'
          server-id: axoniq-nexus
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build and verify
        run: ./mvnw -B -U clean verify
